spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/task_agile?useSSL=false
    username: jmlim
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
