app.mail-from: noreply@gmail.com

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://192.168.219.108:3306/task_agile?useSSL=false
    username: jmlim
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/mail-templates/
  mail:
    host: smtp.gmail.com #localhost
    port: 587 #1025
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    username: username@mail.com
    password: password

logging:
  level:
    io.jmlim.taskagile: DEBUG
    org.springframework.security: DEBUG