spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://192.168.219.108:3306/task_agile?useSSL=false
    username: jmlim
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
